package com.fahlepyrizal01.core.utils

import com.fahlepyrizal01.core.data.source.local.entity.*
import com.fahlepyrizal01.core.data.source.remote.response.*
import com.fahlepyrizal01.core.domain.model.*

object DataMapper {

    object LeagueMapper {
        fun mapResponsesToEntities(input: List<LeagueResponse>): List<LeaguesEntity> {
            val dataList = ArrayList<LeaguesEntity>()
            input.map {
                val data = LeaguesEntity(
                    idLeague = it.idLeague,
                    strLeague = it.strLeague,
                    strSport = it.strSport,
                    strLeagueAlternate = it.strLeagueAlternate
                )
                dataList.add(data)
            }
            return dataList
        }

        fun mapEntitiesToDomain(input: List<LeaguesEntity>): List<League> {
            return input.map {
                League(
                    idLeague = it.idLeague,
                    strLeague = it.strLeague,
                    strSport = it.strSport,
                    strLeagueAlternate = it.strLeagueAlternate
                )
            }
        }
    }

    object LeagueDetailMapper {
        fun mapResponsesToEntities(input: LeagueDetailResponse): LeagueEntity {
            return LeagueEntity(
                idLeague = input.idLeague,
                dateFirstEvent = input.dateFirstEvent,
                idAPIfootball = input.idAPIfootball,
                idCup = input.idCup,
                idSoccerXML = input.idSoccerXML,
                intFormedYear = input.intFormedYear,
                strBadge = input.strBadge,
                strBanner = input.strBanner,
                strComplete = input.strComplete,
                strCountry = input.strCountry,
                strCurrentSeason = input.strCurrentSeason,
                strDescriptionCN = input.strDescriptionCN,
                strDescriptionDE = input.strDescriptionDE,
                strDescriptionEN = input.strDescriptionEN,
                strDescriptionES = input.strDescriptionES,
                strDescriptionFR = input.strDescriptionFR,
                strDescriptionHU = input.strDescriptionHU,
                strDescriptionIL = input.strDescriptionIL,
                strDescriptionIT = input.strDescriptionIT,
                strDescriptionJP = input.strDescriptionJP,
                strDescriptionNL = input.strDescriptionNL,
                strDescriptionNO = input.strDescriptionNO,
                strDescriptionPL = input.strDescriptionPL,
                strDescriptionPT = input.strDescriptionPT,
                strDescriptionRU = input.strDescriptionRU,
                strDescriptionSE = input.strDescriptionSE,
                strDivision = input.strDivision,
                strFacebook = input.strFacebook,
                strFanart1 = input.strFanart1,
                strFanart2 = input.strFanart2,
                strFanart3 = input.strFanart3,
                strFanart4 = input.strFanart4,
                strGender = input.strGender,
                strLeague = input.strLeague,
                strLeagueAlternate = input.strLeagueAlternate,
                strLocked = input.strLocked,
                strLogo = input.strLogo,
                strNaming = input.strNaming,
                strPoster = input.strPoster,
                strRSS = input.strRSS,
                strSport = input.strSport,
                strTrophy = input.strTrophy,
                strTwitter = input.strTwitter,
                strWebsite = input.strWebsite,
                strYoutube = input.strYoutube
            )
        }

        fun mapEntitiesToDomain(input: LeagueEntity?): LeagueDetail {
            return LeagueDetail(
                idLeague = input?.idLeague.orEmpty(),
                dateFirstEvent = input?.dateFirstEvent,
                idAPIfootball = input?.idAPIfootball,
                idCup = input?.idCup,
                idSoccerXML = input?.idSoccerXML,
                intFormedYear = input?.intFormedYear,
                strBadge = input?.strBadge,
                strBanner = input?.strBanner,
                strComplete = input?.strComplete,
                strCountry = input?.strCountry,
                strCurrentSeason = input?.strCurrentSeason,
                strDescriptionCN = input?.strDescriptionCN,
                strDescriptionDE = input?.strDescriptionDE,
                strDescriptionEN = input?.strDescriptionEN,
                strDescriptionES = input?.strDescriptionES,
                strDescriptionFR = input?.strDescriptionFR,
                strDescriptionHU = input?.strDescriptionHU,
                strDescriptionIL = input?.strDescriptionIL,
                strDescriptionIT = input?.strDescriptionIT,
                strDescriptionJP = input?.strDescriptionJP,
                strDescriptionNL = input?.strDescriptionNL,
                strDescriptionNO = input?.strDescriptionNO,
                strDescriptionPL = input?.strDescriptionPL,
                strDescriptionPT = input?.strDescriptionPT,
                strDescriptionRU = input?.strDescriptionRU,
                strDescriptionSE = input?.strDescriptionSE,
                strDivision = input?.strDivision,
                strFacebook = input?.strFacebook,
                strFanart1 = input?.strFanart1,
                strFanart2 = input?.strFanart2,
                strFanart3 = input?.strFanart3,
                strFanart4 = input?.strFanart4,
                strGender = input?.strGender,
                strLeague = input?.strLeague,
                strLeagueAlternate = input?.strLeagueAlternate,
                strLocked = input?.strLocked,
                strLogo = input?.strLogo,
                strNaming = input?.strNaming,
                strPoster = input?.strPoster,
                strRSS = input?.strRSS,
                strSport = input?.strSport,
                strTrophy = input?.strTrophy,
                strTwitter = input?.strTwitter,
                strWebsite = input?.strWebsite,
                strYoutube = input?.strYoutube
            )
        }
    }

    object StandingMapper {
        fun mapResponsesToEntities(
            input: List<StandingResponse>,
            idLeague: String
        ): List<StandingsEntity> {
            val dataList = ArrayList<StandingsEntity>()
            input.map {
                val data = StandingsEntity(
                    idLeague = idLeague,
                    teamid = it.teamid,
                    name = it.name,
                    played = it.played,
                    goalsfor = it.goalsfor,
                    goalsagainst = it.goalsagainst,
                    goalsdifference = it.goalsdifference,
                    win = it.win,
                    draw = it.draw,
                    loss = it.loss,
                    total = it.total,
                )
                dataList.add(data)
            }
            return dataList
        }

        fun mapEntitiesToDomain(input: List<StandingsEntity>): List<Standing> {
            return input.map {
                Standing(
                    idLeague = it.idLeague,
                    teamid = it.teamid,
                    name = it.name,
                    played = it.played,
                    goalsfor = it.goalsfor,
                    goalsagainst = it.goalsagainst,
                    goalsdifference = it.goalsdifference,
                    win = it.win,
                    draw = it.draw,
                    loss = it.loss,
                    total = it.total,
                )
            }
        }
    }

    object TeamMapper {
        fun mapResponsesToEntities(input: List<TeamResponse>, oldData: List<TeamsEntity>?): List<TeamsEntity> {
            val dataList = ArrayList<TeamsEntity>()
            input.map {
                val data = TeamsEntity(
                    idTeam = it.idTeam,
                    idLeague = it.idLeague,
                    idAPIfootball = it.idAPIfootball,
                    idLeague2 = it.idLeague2,
                    idLeague3 = it.idLeague3,
                    idLeague4 = it.idLeague4,
                    idLeague5 = it.idLeague5,
                    idLeague6 = it.idLeague6,
                    idLeague7 = it.idLeague7,
                    idSoccerXML = it.idSoccerXML,
                    intFormedYear = it.intFormedYear,
                    intLoved = it.intLoved,
                    intStadiumCapacity = it.intStadiumCapacity,
                    strAlternate = it.strAlternate,
                    strCountry = it.strCountry,
                    strDescriptionCN = it.strDescriptionCN,
                    strDescriptionDE = it.strDescriptionDE,
                    strDescriptionEN = it.strDescriptionEN,
                    strDescriptionES = it.strDescriptionES,
                    strDescriptionFR = it.strDescriptionFR,
                    strDescriptionHU = it.strDescriptionHU,
                    strDescriptionIL = it.strDescriptionIL,
                    strDescriptionIT = it.strDescriptionIT,
                    strDescriptionJP = it.strDescriptionJP,
                    strDescriptionNL = it.strDescriptionNL,
                    strDescriptionNO = it.strDescriptionNO,
                    strDescriptionPL = it.strDescriptionPL,
                    strDescriptionPT = it.strDescriptionPT,
                    strDescriptionRU = it.strDescriptionRU,
                    strDescriptionSE = it.strDescriptionSE,
                    strDivision = it.strDivision,
                    strFacebook = it.strFacebook,
                    strGender = it.strGender,
                    strInstagram = it.strInstagram,
                    strKeywords = it.strKeywords,
                    strLeague = it.strLeague,
                    strLeague2 = it.strLeague2,
                    strLeague3 = it.strLeague3,
                    strLeague4 = it.strLeague4,
                    strLeague5 = it.strLeague5,
                    strLeague6 = it.strLeague6,
                    strLeague7 = it.strLeague7,
                    strLocked = it.strLocked,
                    strManager = it.strManager,
                    strRSS = it.strRSS,
                    strSport = it.strSport,
                    strStadium = it.strStadium,
                    strStadiumDescription = it.strStadiumDescription,
                    strStadiumLocation = it.strStadiumLocation,
                    strStadiumThumb = it.strStadiumThumb,
                    strTeam = it.strTeam,
                    strTeamBadge = it.strTeamBadge,
                    strTeamBanner = it.strTeamBanner,
                    strTeamFanart1 = it.strTeamFanart1,
                    strTeamFanart2 = it.strTeamFanart2,
                    strTeamFanart3 = it.strTeamFanart3,
                    strTeamFanart4 = it.strTeamFanart4,
                    strTeamJersey = it.strTeamJersey,
                    strTeamLogo = it.strTeamLogo,
                    strTeamShort = it.strTeamShort,
                    strTwitter = it.strTwitter,
                    strWebsite = it.strWebsite,
                    strYoutube = it.strYoutube,
                    isFavorite = oldData?.find { team -> team.idTeam == it.idTeam }?.isFavorite ?: false
                )
                dataList.add(data)
            }
            return dataList
        }

        fun mapEntitiesToDomain(input: List<TeamsEntity>): List<Team> {
            return input.map {
                Team(
                    idTeam = it.idTeam,
                    idLeague = it.idLeague,
                    idAPIfootball = it.idAPIfootball,
                    idLeague2 = it.idLeague2,
                    idLeague3 = it.idLeague3,
                    idLeague4 = it.idLeague4,
                    idLeague5 = it.idLeague5,
                    idLeague6 = it.idLeague6,
                    idLeague7 = it.idLeague7,
                    idSoccerXML = it.idSoccerXML,
                    intFormedYear = it.intFormedYear,
                    intLoved = it.intLoved,
                    intStadiumCapacity = it.intStadiumCapacity,
                    strAlternate = it.strAlternate,
                    strCountry = it.strCountry,
                    strDescriptionCN = it.strDescriptionCN,
                    strDescriptionDE = it.strDescriptionDE,
                    strDescriptionEN = it.strDescriptionEN,
                    strDescriptionES = it.strDescriptionES,
                    strDescriptionFR = it.strDescriptionFR,
                    strDescriptionHU = it.strDescriptionHU,
                    strDescriptionIL = it.strDescriptionIL,
                    strDescriptionIT = it.strDescriptionIT,
                    strDescriptionJP = it.strDescriptionJP,
                    strDescriptionNL = it.strDescriptionNL,
                    strDescriptionNO = it.strDescriptionNO,
                    strDescriptionPL = it.strDescriptionPL,
                    strDescriptionPT = it.strDescriptionPT,
                    strDescriptionRU = it.strDescriptionRU,
                    strDescriptionSE = it.strDescriptionSE,
                    strDivision = it.strDivision,
                    strFacebook = it.strFacebook,
                    strGender = it.strGender,
                    strInstagram = it.strInstagram,
                    strKeywords = it.strKeywords,
                    strLeague = it.strLeague,
                    strLeague2 = it.strLeague2,
                    strLeague3 = it.strLeague3,
                    strLeague4 = it.strLeague4,
                    strLeague5 = it.strLeague5,
                    strLeague6 = it.strLeague6,
                    strLeague7 = it.strLeague7,
                    strLocked = it.strLocked,
                    strManager = it.strManager,
                    strRSS = it.strRSS,
                    strSport = it.strSport,
                    strStadium = it.strStadium,
                    strStadiumDescription = it.strStadiumDescription,
                    strStadiumLocation = it.strStadiumLocation,
                    strStadiumThumb = it.strStadiumThumb,
                    strTeam = it.strTeam,
                    strTeamBadge = it.strTeamBadge,
                    strTeamBanner = it.strTeamBanner,
                    strTeamFanart1 = it.strTeamFanart1,
                    strTeamFanart2 = it.strTeamFanart2,
                    strTeamFanart3 = it.strTeamFanart3,
                    strTeamFanart4 = it.strTeamFanart4,
                    strTeamJersey = it.strTeamJersey,
                    strTeamLogo = it.strTeamLogo,
                    strTeamShort = it.strTeamShort,
                    strTwitter = it.strTwitter,
                    strWebsite = it.strWebsite,
                    strYoutube = it.strYoutube,
                    isFavorite = it.isFavorite
                )
            }
        }
    }

    object TeamDetailMapper {
        fun mapResponsesToEntities(input: TeamResponse, oldData: TeamsEntity?): TeamsEntity {
            return TeamsEntity(
                idTeam = input.idTeam,
                idLeague = input.idLeague,
                idAPIfootball = input.idAPIfootball,
                idLeague2 = input.idLeague2,
                idLeague3 = input.idLeague3,
                idLeague4 = input.idLeague4,
                idLeague5 = input.idLeague5,
                idLeague6 = input.idLeague6,
                idLeague7 = input.idLeague7,
                idSoccerXML = input.idSoccerXML,
                intFormedYear = input.intFormedYear,
                intLoved = input.intLoved,
                intStadiumCapacity = input.intStadiumCapacity,
                strAlternate = input.strAlternate,
                strCountry = input.strCountry,
                strDescriptionCN = input.strDescriptionCN,
                strDescriptionDE = input.strDescriptionDE,
                strDescriptionEN = input.strDescriptionEN,
                strDescriptionES = input.strDescriptionES,
                strDescriptionFR = input.strDescriptionFR,
                strDescriptionHU = input.strDescriptionHU,
                strDescriptionIL = input.strDescriptionIL,
                strDescriptionIT = input.strDescriptionIT,
                strDescriptionJP = input.strDescriptionJP,
                strDescriptionNL = input.strDescriptionNL,
                strDescriptionNO = input.strDescriptionNO,
                strDescriptionPL = input.strDescriptionPL,
                strDescriptionPT = input.strDescriptionPT,
                strDescriptionRU = input.strDescriptionRU,
                strDescriptionSE = input.strDescriptionSE,
                strDivision = input.strDivision,
                strFacebook = input.strFacebook,
                strGender = input.strGender,
                strInstagram = input.strInstagram,
                strKeywords = input.strKeywords,
                strLeague = input.strLeague,
                strLeague2 = input.strLeague2,
                strLeague3 = input.strLeague3,
                strLeague4 = input.strLeague4,
                strLeague5 = input.strLeague5,
                strLeague6 = input.strLeague6,
                strLeague7 = input.strLeague7,
                strLocked = input.strLocked,
                strManager = input.strManager,
                strRSS = input.strRSS,
                strSport = input.strSport,
                strStadium = input.strStadium,
                strStadiumDescription = input.strStadiumDescription,
                strStadiumLocation = input.strStadiumLocation,
                strStadiumThumb = input.strStadiumThumb,
                strTeam = input.strTeam,
                strTeamBadge = input.strTeamBadge,
                strTeamBanner = input.strTeamBanner,
                strTeamFanart1 = input.strTeamFanart1,
                strTeamFanart2 = input.strTeamFanart2,
                strTeamFanart3 = input.strTeamFanart3,
                strTeamFanart4 = input.strTeamFanart4,
                strTeamJersey = input.strTeamJersey,
                strTeamLogo = input.strTeamLogo,
                strTeamShort = input.strTeamShort,
                strTwitter = input.strTwitter,
                strWebsite = input.strWebsite,
                strYoutube = input.strYoutube,
                isFavorite = oldData?.isFavorite ?: false
            )
        }

        fun mapEntitiesToDomain(input: TeamsEntity?): Team {
            return Team(
                idTeam = input?.idTeam.orEmpty(),
                idLeague = input?.idLeague.orEmpty(),
                idAPIfootball = input?.idAPIfootball,
                idLeague2 = input?.idLeague2,
                idLeague3 = input?.idLeague3,
                idLeague4 = input?.idLeague4,
                idLeague5 = input?.idLeague5,
                idLeague6 = input?.idLeague6,
                idLeague7 = input?.idLeague7,
                idSoccerXML = input?.idSoccerXML,
                intFormedYear = input?.intFormedYear,
                intLoved = input?.intLoved,
                intStadiumCapacity = input?.intStadiumCapacity,
                strAlternate = input?.strAlternate,
                strCountry = input?.strCountry,
                strDescriptionCN = input?.strDescriptionCN,
                strDescriptionDE = input?.strDescriptionDE,
                strDescriptionEN = input?.strDescriptionEN,
                strDescriptionES = input?.strDescriptionES,
                strDescriptionFR = input?.strDescriptionFR,
                strDescriptionHU = input?.strDescriptionHU,
                strDescriptionIL = input?.strDescriptionIL,
                strDescriptionIT = input?.strDescriptionIT,
                strDescriptionJP = input?.strDescriptionJP,
                strDescriptionNL = input?.strDescriptionNL,
                strDescriptionNO = input?.strDescriptionNO,
                strDescriptionPL = input?.strDescriptionPL,
                strDescriptionPT = input?.strDescriptionPT,
                strDescriptionRU = input?.strDescriptionRU,
                strDescriptionSE = input?.strDescriptionSE,
                strDivision = input?.strDivision,
                strFacebook = input?.strFacebook,
                strGender = input?.strGender,
                strInstagram = input?.strInstagram,
                strKeywords = input?.strKeywords,
                strLeague = input?.strLeague,
                strLeague2 = input?.strLeague2,
                strLeague3 = input?.strLeague3,
                strLeague4 = input?.strLeague4,
                strLeague5 = input?.strLeague5,
                strLeague6 = input?.strLeague6,
                strLeague7 = input?.strLeague7,
                strLocked = input?.strLocked,
                strManager = input?.strManager,
                strRSS = input?.strRSS,
                strSport = input?.strSport,
                strStadium = input?.strStadium,
                strStadiumDescription = input?.strStadiumDescription,
                strStadiumLocation = input?.strStadiumLocation,
                strStadiumThumb = input?.strStadiumThumb,
                strTeam = input?.strTeam,
                strTeamBadge = input?.strTeamBadge,
                strTeamBanner = input?.strTeamBanner,
                strTeamFanart1 = input?.strTeamFanart1,
                strTeamFanart2 = input?.strTeamFanart2,
                strTeamFanart3 = input?.strTeamFanart3,
                strTeamFanart4 = input?.strTeamFanart4,
                strTeamJersey = input?.strTeamJersey,
                strTeamLogo = input?.strTeamLogo,
                strTeamShort = input?.strTeamShort,
                strTwitter = input?.strTwitter,
                strWebsite = input?.strWebsite,
                strYoutube = input?.strYoutube,
                isFavorite = input?.isFavorite
            )
        }

        fun mapDomainToEntity(input: Team, isFavorite: Boolean) = TeamsEntity(
            idTeam = input.idTeam,
            idLeague = input.idLeague,
            idAPIfootball = input.idAPIfootball,
            idLeague2 = input.idLeague2,
            idLeague3 = input.idLeague3,
            idLeague4 = input.idLeague4,
            idLeague5 = input.idLeague5,
            idLeague6 = input.idLeague6,
            idLeague7 = input.idLeague7,
            idSoccerXML = input.idSoccerXML,
            intFormedYear = input.intFormedYear,
            intLoved = input.intLoved,
            intStadiumCapacity = input.intStadiumCapacity,
            strAlternate = input.strAlternate,
            strCountry = input.strCountry,
            strDescriptionCN = input.strDescriptionCN,
            strDescriptionDE = input.strDescriptionDE,
            strDescriptionEN = input.strDescriptionEN,
            strDescriptionES = input.strDescriptionES,
            strDescriptionFR = input.strDescriptionFR,
            strDescriptionHU = input.strDescriptionHU,
            strDescriptionIL = input.strDescriptionIL,
            strDescriptionIT = input.strDescriptionIT,
            strDescriptionJP = input.strDescriptionJP,
            strDescriptionNL = input.strDescriptionNL,
            strDescriptionNO = input.strDescriptionNO,
            strDescriptionPL = input.strDescriptionPL,
            strDescriptionPT = input.strDescriptionPT,
            strDescriptionRU = input.strDescriptionRU,
            strDescriptionSE = input.strDescriptionSE,
            strDivision = input.strDivision,
            strFacebook = input.strFacebook,
            strGender = input.strGender,
            strInstagram = input.strInstagram,
            strKeywords = input.strKeywords,
            strLeague = input.strLeague,
            strLeague2 = input.strLeague2,
            strLeague3 = input.strLeague3,
            strLeague4 = input.strLeague4,
            strLeague5 = input.strLeague5,
            strLeague6 = input.strLeague6,
            strLeague7 = input.strLeague7,
            strLocked = input.strLocked,
            strManager = input.strManager,
            strRSS = input.strRSS,
            strSport = input.strSport,
            strStadium = input.strStadium,
            strStadiumDescription = input.strStadiumDescription,
            strStadiumLocation = input.strStadiumLocation,
            strStadiumThumb = input.strStadiumThumb,
            strTeam = input.strTeam,
            strTeamBadge = input.strTeamBadge,
            strTeamBanner = input.strTeamBanner,
            strTeamFanart1 = input.strTeamFanart1,
            strTeamFanart2 = input.strTeamFanart2,
            strTeamFanart3 = input.strTeamFanart3,
            strTeamFanart4 = input.strTeamFanart4,
            strTeamJersey = input.strTeamJersey,
            strTeamLogo = input.strTeamLogo,
            strTeamShort = input.strTeamShort,
            strTwitter = input.strTwitter,
            strWebsite = input.strWebsite,
            strYoutube = input.strYoutube,
            isFavorite = isFavorite
        )
    }

    object EventMapper {
        fun lastMapResponsesToEntities(input: List<EventResponse>): List<LastEventsEntity> {
            val dataList = ArrayList<LastEventsEntity>()
            input.map {
                val data = LastEventsEntity(
                    idEvent = it.idEvent,
                    idLeague = it.idLeague,
                    idAwayTeam = it.idAwayTeam,
                    idHomeTeam = it.idHomeTeam,
                    dateEvent = it.dateEvent,
                    dateEventLocal = it.dateEventLocal,
                    idAPIfootball = it.idAPIfootball,
                    idSoccerXML = it.idSoccerXML,
                    intAwayScore = it.intAwayScore,
                    intAwayShots = it.intAwayShots,
                    intHomeScore = it.intHomeScore,
                    intHomeShots = it.intHomeShots,
                    intRound = it.intRound,
                    intSpectators = it.intSpectators,
                    strAwayFormation = it.strAwayFormation,
                    strAwayGoalDetails = it.strAwayGoalDetails,
                    strAwayLineupDefense = it.strAwayLineupDefense,
                    strAwayLineupForward = it.strAwayLineupForward,
                    strAwayLineupGoalkeeper = it.strAwayLineupGoalkeeper,
                    strAwayLineupMidfield = it.strAwayLineupMidfield,
                    strAwayLineupSubstitutes = it.strAwayLineupSubstitutes,
                    strAwayRedCards = it.strAwayRedCards,
                    strAwayTeam = it.strAwayTeam,
                    strAwayYellowCards = it.strAwayYellowCards,
                    strBanner = it.strBanner,
                    strCity = it.strCity,
                    strCountry = it.strCountry,
                    strDate = it.strDate,
                    strDescriptionEN = it.strDescriptionEN,
                    strEvent = it.strEvent,
                    strEventAlternate = it.strEventAlternate,
                    strFanart = it.strFanart,
                    strFilename = it.strFilename,
                    strHomeFormation = it.strHomeFormation,
                    strHomeGoalDetails = it.strHomeGoalDetails,
                    strHomeLineupDefense = it.strHomeLineupDefense,
                    strHomeLineupForward = it.strHomeLineupForward,
                    strHomeLineupGoalkeeper = it.strHomeLineupGoalkeeper,
                    strHomeLineupMidfield = it.strHomeLineupMidfield,
                    strHomeLineupSubstitutes = it.strHomeLineupSubstitutes,
                    strHomeRedCards = it.strHomeRedCards,
                    strHomeTeam = it.strHomeTeam,
                    strHomeYellowCards = it.strHomeYellowCards,
                    strLeague = it.strLeague,
                    strLocked = it.strLocked,
                    strMap = it.strMap,
                    strOfficial = it.strOfficial,
                    strPoster = it.strPoster,
                    strPostponed = it.strPostponed,
                    strResult = it.strResult,
                    strSeason = it.strSeason,
                    strSport = it.strSport,
                    strStatus = it.strStatus,
                    strTVStation = it.strTVStation,
                    strThumb = it.strThumb,
                    strTime = it.strTime,
                    strTimeLocal = it.strTimeLocal,
                    strTimestamp = it.strTimestamp,
                    strTweet1 = it.strTweet1,
                    strTweet2 = it.strTweet2,
                    strTweet3 = it.strTweet3,
                    strVenue = it.strVenue,
                    strVideo = it.strVideo
                )
                dataList.add(data)
            }
            return dataList
        }

        fun lastMapEntitiesToDomain(input: List<LastEventsEntity>): List<Event> {
            return input.map {
                Event(
                    idEvent = it.idEvent,
                    idLeague = it.idLeague,
                    idAwayTeam = it.idAwayTeam,
                    idHomeTeam = it.idHomeTeam,
                    dateEvent = it.dateEvent,
                    dateEventLocal = it.dateEventLocal,
                    idAPIfootball = it.idAPIfootball,
                    idSoccerXML = it.idSoccerXML,
                    intAwayScore = it.intAwayScore,
                    intAwayShots = it.intAwayShots,
                    intHomeScore = it.intHomeScore,
                    intHomeShots = it.intHomeShots,
                    intRound = it.intRound,
                    intSpectators = it.intSpectators,
                    strAwayFormation = it.strAwayFormation,
                    strAwayGoalDetails = it.strAwayGoalDetails,
                    strAwayLineupDefense = it.strAwayLineupDefense,
                    strAwayLineupForward = it.strAwayLineupForward,
                    strAwayLineupGoalkeeper = it.strAwayLineupGoalkeeper,
                    strAwayLineupMidfield = it.strAwayLineupMidfield,
                    strAwayLineupSubstitutes = it.strAwayLineupSubstitutes,
                    strAwayRedCards = it.strAwayRedCards,
                    strAwayTeam = it.strAwayTeam,
                    strAwayYellowCards = it.strAwayYellowCards,
                    strBanner = it.strBanner,
                    strCity = it.strCity,
                    strCountry = it.strCountry,
                    strDate = it.strDate,
                    strDescriptionEN = it.strDescriptionEN,
                    strEvent = it.strEvent,
                    strEventAlternate = it.strEventAlternate,
                    strFanart = it.strFanart,
                    strFilename = it.strFilename,
                    strHomeFormation = it.strHomeFormation,
                    strHomeGoalDetails = it.strHomeGoalDetails,
                    strHomeLineupDefense = it.strHomeLineupDefense,
                    strHomeLineupForward = it.strHomeLineupForward,
                    strHomeLineupGoalkeeper = it.strHomeLineupGoalkeeper,
                    strHomeLineupMidfield = it.strHomeLineupMidfield,
                    strHomeLineupSubstitutes = it.strHomeLineupSubstitutes,
                    strHomeRedCards = it.strHomeRedCards,
                    strHomeTeam = it.strHomeTeam,
                    strHomeYellowCards = it.strHomeYellowCards,
                    strLeague = it.strLeague,
                    strLocked = it.strLocked,
                    strMap = it.strMap,
                    strOfficial = it.strOfficial,
                    strPoster = it.strPoster,
                    strPostponed = it.strPostponed,
                    strResult = it.strResult,
                    strSeason = it.strSeason,
                    strSport = it.strSport,
                    strStatus = it.strStatus,
                    strTVStation = it.strTVStation,
                    strThumb = it.strThumb,
                    strTime = it.strTime,
                    strTimeLocal = it.strTimeLocal,
                    strTimestamp = it.strTimestamp,
                    strTweet1 = it.strTweet1,
                    strTweet2 = it.strTweet2,
                    strTweet3 = it.strTweet3,
                    strVenue = it.strVenue,
                    strVideo = it.strVideo
                )
            }
        }

        fun nextMapResponsesToEntities(input: List<EventResponse>): List<NextEventsEntity> {
            val dataList = ArrayList<NextEventsEntity>()
            input.map {
                val data = NextEventsEntity(
                    idEvent = it.idEvent,
                    idLeague = it.idLeague,
                    idAwayTeam = it.idAwayTeam,
                    idHomeTeam = it.idHomeTeam,
                    dateEvent = it.dateEvent,
                    dateEventLocal = it.dateEventLocal,
                    idAPIfootball = it.idAPIfootball,
                    idSoccerXML = it.idSoccerXML,
                    intAwayScore = it.intAwayScore,
                    intAwayShots = it.intAwayShots,
                    intHomeScore = it.intHomeScore,
                    intHomeShots = it.intHomeShots,
                    intRound = it.intRound,
                    intSpectators = it.intSpectators,
                    strAwayFormation = it.strAwayFormation,
                    strAwayGoalDetails = it.strAwayGoalDetails,
                    strAwayLineupDefense = it.strAwayLineupDefense,
                    strAwayLineupForward = it.strAwayLineupForward,
                    strAwayLineupGoalkeeper = it.strAwayLineupGoalkeeper,
                    strAwayLineupMidfield = it.strAwayLineupMidfield,
                    strAwayLineupSubstitutes = it.strAwayLineupSubstitutes,
                    strAwayRedCards = it.strAwayRedCards,
                    strAwayTeam = it.strAwayTeam,
                    strAwayYellowCards = it.strAwayYellowCards,
                    strBanner = it.strBanner,
                    strCity = it.strCity,
                    strCountry = it.strCountry,
                    strDate = it.strDate,
                    strDescriptionEN = it.strDescriptionEN,
                    strEvent = it.strEvent,
                    strEventAlternate = it.strEventAlternate,
                    strFanart = it.strFanart,
                    strFilename = it.strFilename,
                    strHomeFormation = it.strHomeFormation,
                    strHomeGoalDetails = it.strHomeGoalDetails,
                    strHomeLineupDefense = it.strHomeLineupDefense,
                    strHomeLineupForward = it.strHomeLineupForward,
                    strHomeLineupGoalkeeper = it.strHomeLineupGoalkeeper,
                    strHomeLineupMidfield = it.strHomeLineupMidfield,
                    strHomeLineupSubstitutes = it.strHomeLineupSubstitutes,
                    strHomeRedCards = it.strHomeRedCards,
                    strHomeTeam = it.strHomeTeam,
                    strHomeYellowCards = it.strHomeYellowCards,
                    strLeague = it.strLeague,
                    strLocked = it.strLocked,
                    strMap = it.strMap,
                    strOfficial = it.strOfficial,
                    strPoster = it.strPoster,
                    strPostponed = it.strPostponed,
                    strResult = it.strResult,
                    strSeason = it.strSeason,
                    strSport = it.strSport,
                    strStatus = it.strStatus,
                    strTVStation = it.strTVStation,
                    strThumb = it.strThumb,
                    strTime = it.strTime,
                    strTimeLocal = it.strTimeLocal,
                    strTimestamp = it.strTimestamp,
                    strTweet1 = it.strTweet1,
                    strTweet2 = it.strTweet2,
                    strTweet3 = it.strTweet3,
                    strVenue = it.strVenue,
                    strVideo = it.strVideo
                )
                dataList.add(data)
            }
            return dataList
        }

        fun nextMapEntitiesToDomain(input: List<NextEventsEntity>): List<Event> {
            return input.map {
                Event(
                    idEvent = it.idEvent,
                    idLeague = it.idLeague,
                    idAwayTeam = it.idAwayTeam,
                    idHomeTeam = it.idHomeTeam,
                    dateEvent = it.dateEvent,
                    dateEventLocal = it.dateEventLocal,
                    idAPIfootball = it.idAPIfootball,
                    idSoccerXML = it.idSoccerXML,
                    intAwayScore = it.intAwayScore,
                    intAwayShots = it.intAwayShots,
                    intHomeScore = it.intHomeScore,
                    intHomeShots = it.intHomeShots,
                    intRound = it.intRound,
                    intSpectators = it.intSpectators,
                    strAwayFormation = it.strAwayFormation,
                    strAwayGoalDetails = it.strAwayGoalDetails,
                    strAwayLineupDefense = it.strAwayLineupDefense,
                    strAwayLineupForward = it.strAwayLineupForward,
                    strAwayLineupGoalkeeper = it.strAwayLineupGoalkeeper,
                    strAwayLineupMidfield = it.strAwayLineupMidfield,
                    strAwayLineupSubstitutes = it.strAwayLineupSubstitutes,
                    strAwayRedCards = it.strAwayRedCards,
                    strAwayTeam = it.strAwayTeam,
                    strAwayYellowCards = it.strAwayYellowCards,
                    strBanner = it.strBanner,
                    strCity = it.strCity,
                    strCountry = it.strCountry,
                    strDate = it.strDate,
                    strDescriptionEN = it.strDescriptionEN,
                    strEvent = it.strEvent,
                    strEventAlternate = it.strEventAlternate,
                    strFanart = it.strFanart,
                    strFilename = it.strFilename,
                    strHomeFormation = it.strHomeFormation,
                    strHomeGoalDetails = it.strHomeGoalDetails,
                    strHomeLineupDefense = it.strHomeLineupDefense,
                    strHomeLineupForward = it.strHomeLineupForward,
                    strHomeLineupGoalkeeper = it.strHomeLineupGoalkeeper,
                    strHomeLineupMidfield = it.strHomeLineupMidfield,
                    strHomeLineupSubstitutes = it.strHomeLineupSubstitutes,
                    strHomeRedCards = it.strHomeRedCards,
                    strHomeTeam = it.strHomeTeam,
                    strHomeYellowCards = it.strHomeYellowCards,
                    strLeague = it.strLeague,
                    strLocked = it.strLocked,
                    strMap = it.strMap,
                    strOfficial = it.strOfficial,
                    strPoster = it.strPoster,
                    strPostponed = it.strPostponed,
                    strResult = it.strResult,
                    strSeason = it.strSeason,
                    strSport = it.strSport,
                    strStatus = it.strStatus,
                    strTVStation = it.strTVStation,
                    strThumb = it.strThumb,
                    strTime = it.strTime,
                    strTimeLocal = it.strTimeLocal,
                    strTimestamp = it.strTimestamp,
                    strTweet1 = it.strTweet1,
                    strTweet2 = it.strTweet2,
                    strTweet3 = it.strTweet3,
                    strVenue = it.strVenue,
                    strVideo = it.strVideo
                )
            }
        }
    }

    object EventDetailMapper {
        fun lastMapResponsesToEntities(input: EventResponse): LastEventsEntity {
            return LastEventsEntity(
                idEvent = input.idEvent,
                idLeague = input.idLeague,
                idAwayTeam = input.idAwayTeam,
                idHomeTeam = input.idHomeTeam,
                dateEvent = input.dateEvent,
                dateEventLocal = input.dateEventLocal,
                idAPIfootball = input.idAPIfootball,
                idSoccerXML = input.idSoccerXML,
                intAwayScore = input.intAwayScore,
                intAwayShots = input.intAwayShots,
                intHomeScore = input.intHomeScore,
                intHomeShots = input.intHomeShots,
                intRound = input.intRound,
                intSpectators = input.intSpectators,
                strAwayFormation = input.strAwayFormation,
                strAwayGoalDetails = input.strAwayGoalDetails,
                strAwayLineupDefense = input.strAwayLineupDefense,
                strAwayLineupForward = input.strAwayLineupForward,
                strAwayLineupGoalkeeper = input.strAwayLineupGoalkeeper,
                strAwayLineupMidfield = input.strAwayLineupMidfield,
                strAwayLineupSubstitutes = input.strAwayLineupSubstitutes,
                strAwayRedCards = input.strAwayRedCards,
                strAwayTeam = input.strAwayTeam,
                strAwayYellowCards = input.strAwayYellowCards,
                strBanner = input.strBanner,
                strCity = input.strCity,
                strCountry = input.strCountry,
                strDate = input.strDate,
                strDescriptionEN = input.strDescriptionEN,
                strEvent = input.strEvent,
                strEventAlternate = input.strEventAlternate,
                strFanart = input.strFanart,
                strFilename = input.strFilename,
                strHomeFormation = input.strHomeFormation,
                strHomeGoalDetails = input.strHomeGoalDetails,
                strHomeLineupDefense = input.strHomeLineupDefense,
                strHomeLineupForward = input.strHomeLineupForward,
                strHomeLineupGoalkeeper = input.strHomeLineupGoalkeeper,
                strHomeLineupMidfield = input.strHomeLineupMidfield,
                strHomeLineupSubstitutes = input.strHomeLineupSubstitutes,
                strHomeRedCards = input.strHomeRedCards,
                strHomeTeam = input.strHomeTeam,
                strHomeYellowCards = input.strHomeYellowCards,
                strLeague = input.strLeague,
                strLocked = input.strLocked,
                strMap = input.strMap,
                strOfficial = input.strOfficial,
                strPoster = input.strPoster,
                strPostponed = input.strPostponed,
                strResult = input.strResult,
                strSeason = input.strSeason,
                strSport = input.strSport,
                strStatus = input.strStatus,
                strTVStation = input.strTVStation,
                strThumb = input.strThumb,
                strTime = input.strTime,
                strTimeLocal = input.strTimeLocal,
                strTimestamp = input.strTimestamp,
                strTweet1 = input.strTweet1,
                strTweet2 = input.strTweet2,
                strTweet3 = input.strTweet3,
                strVenue = input.strVenue,
                strVideo = input.strVideo
            )
        }

        fun lastMapEntitiesToDomain(input: LastEventsEntity?): Event {
            return Event(
                idEvent = input?.idEvent.orEmpty(),
                idLeague = input?.idLeague.orEmpty(),
                idAwayTeam = input?.idAwayTeam.orEmpty(),
                idHomeTeam = input?.idHomeTeam.orEmpty(),
                dateEvent = input?.dateEvent,
                dateEventLocal = input?.dateEventLocal,
                idAPIfootball = input?.idAPIfootball,
                idSoccerXML = input?.idSoccerXML,
                intAwayScore = input?.intAwayScore,
                intAwayShots = input?.intAwayShots,
                intHomeScore = input?.intHomeScore,
                intHomeShots = input?.intHomeShots,
                intRound = input?.intRound,
                intSpectators = input?.intSpectators,
                strAwayFormation = input?.strAwayFormation,
                strAwayGoalDetails = input?.strAwayGoalDetails,
                strAwayLineupDefense = input?.strAwayLineupDefense,
                strAwayLineupForward = input?.strAwayLineupForward,
                strAwayLineupGoalkeeper = input?.strAwayLineupGoalkeeper,
                strAwayLineupMidfield = input?.strAwayLineupMidfield,
                strAwayLineupSubstitutes = input?.strAwayLineupSubstitutes,
                strAwayRedCards = input?.strAwayRedCards,
                strAwayTeam = input?.strAwayTeam,
                strAwayYellowCards = input?.strAwayYellowCards,
                strBanner = input?.strBanner,
                strCity = input?.strCity,
                strCountry = input?.strCountry,
                strDate = input?.strDate,
                strDescriptionEN = input?.strDescriptionEN,
                strEvent = input?.strEvent,
                strEventAlternate = input?.strEventAlternate,
                strFanart = input?.strFanart,
                strFilename = input?.strFilename,
                strHomeFormation = input?.strHomeFormation,
                strHomeGoalDetails = input?.strHomeGoalDetails,
                strHomeLineupDefense = input?.strHomeLineupDefense,
                strHomeLineupForward = input?.strHomeLineupForward,
                strHomeLineupGoalkeeper = input?.strHomeLineupGoalkeeper,
                strHomeLineupMidfield = input?.strHomeLineupMidfield,
                strHomeLineupSubstitutes = input?.strHomeLineupSubstitutes,
                strHomeRedCards = input?.strHomeRedCards,
                strHomeTeam = input?.strHomeTeam,
                strHomeYellowCards = input?.strHomeYellowCards,
                strLeague = input?.strLeague,
                strLocked = input?.strLocked,
                strMap = input?.strMap,
                strOfficial = input?.strOfficial,
                strPoster = input?.strPoster,
                strPostponed = input?.strPostponed,
                strResult = input?.strResult,
                strSeason = input?.strSeason,
                strSport = input?.strSport,
                strStatus = input?.strStatus,
                strTVStation = input?.strTVStation,
                strThumb = input?.strThumb,
                strTime = input?.strTime,
                strTimeLocal = input?.strTimeLocal,
                strTimestamp = input?.strTimestamp,
                strTweet1 = input?.strTweet1,
                strTweet2 = input?.strTweet2,
                strTweet3 = input?.strTweet3,
                strVenue = input?.strVenue,
                strVideo = input?.strVideo
            )
        }

        fun nextMapResponsesToEntities(input: EventResponse): NextEventsEntity {
            return NextEventsEntity(
                idEvent = input.idEvent,
                idLeague = input.idLeague,
                idAwayTeam = input.idAwayTeam,
                idHomeTeam = input.idHomeTeam,
                dateEvent = input.dateEvent,
                dateEventLocal = input.dateEventLocal,
                idAPIfootball = input.idAPIfootball,
                idSoccerXML = input.idSoccerXML,
                intAwayScore = input.intAwayScore,
                intAwayShots = input.intAwayShots,
                intHomeScore = input.intHomeScore,
                intHomeShots = input.intHomeShots,
                intRound = input.intRound,
                intSpectators = input.intSpectators,
                strAwayFormation = input.strAwayFormation,
                strAwayGoalDetails = input.strAwayGoalDetails,
                strAwayLineupDefense = input.strAwayLineupDefense,
                strAwayLineupForward = input.strAwayLineupForward,
                strAwayLineupGoalkeeper = input.strAwayLineupGoalkeeper,
                strAwayLineupMidfield = input.strAwayLineupMidfield,
                strAwayLineupSubstitutes = input.strAwayLineupSubstitutes,
                strAwayRedCards = input.strAwayRedCards,
                strAwayTeam = input.strAwayTeam,
                strAwayYellowCards = input.strAwayYellowCards,
                strBanner = input.strBanner,
                strCity = input.strCity,
                strCountry = input.strCountry,
                strDate = input.strDate,
                strDescriptionEN = input.strDescriptionEN,
                strEvent = input.strEvent,
                strEventAlternate = input.strEventAlternate,
                strFanart = input.strFanart,
                strFilename = input.strFilename,
                strHomeFormation = input.strHomeFormation,
                strHomeGoalDetails = input.strHomeGoalDetails,
                strHomeLineupDefense = input.strHomeLineupDefense,
                strHomeLineupForward = input.strHomeLineupForward,
                strHomeLineupGoalkeeper = input.strHomeLineupGoalkeeper,
                strHomeLineupMidfield = input.strHomeLineupMidfield,
                strHomeLineupSubstitutes = input.strHomeLineupSubstitutes,
                strHomeRedCards = input.strHomeRedCards,
                strHomeTeam = input.strHomeTeam,
                strHomeYellowCards = input.strHomeYellowCards,
                strLeague = input.strLeague,
                strLocked = input.strLocked,
                strMap = input.strMap,
                strOfficial = input.strOfficial,
                strPoster = input.strPoster,
                strPostponed = input.strPostponed,
                strResult = input.strResult,
                strSeason = input.strSeason,
                strSport = input.strSport,
                strStatus = input.strStatus,
                strTVStation = input.strTVStation,
                strThumb = input.strThumb,
                strTime = input.strTime,
                strTimeLocal = input.strTimeLocal,
                strTimestamp = input.strTimestamp,
                strTweet1 = input.strTweet1,
                strTweet2 = input.strTweet2,
                strTweet3 = input.strTweet3,
                strVenue = input.strVenue,
                strVideo = input.strVideo
            )
        }

        fun nextMapEntitiesToDomain(input: NextEventsEntity?): Event {
            return Event(
                idEvent = input?.idEvent.orEmpty(),
                idLeague = input?.idLeague.orEmpty(),
                idAwayTeam = input?.idAwayTeam.orEmpty(),
                idHomeTeam = input?.idHomeTeam.orEmpty(),
                dateEvent = input?.dateEvent,
                dateEventLocal = input?.dateEventLocal,
                idAPIfootball = input?.idAPIfootball,
                idSoccerXML = input?.idSoccerXML,
                intAwayScore = input?.intAwayScore,
                intAwayShots = input?.intAwayShots,
                intHomeScore = input?.intHomeScore,
                intHomeShots = input?.intHomeShots,
                intRound = input?.intRound,
                intSpectators = input?.intSpectators,
                strAwayFormation = input?.strAwayFormation,
                strAwayGoalDetails = input?.strAwayGoalDetails,
                strAwayLineupDefense = input?.strAwayLineupDefense,
                strAwayLineupForward = input?.strAwayLineupForward,
                strAwayLineupGoalkeeper = input?.strAwayLineupGoalkeeper,
                strAwayLineupMidfield = input?.strAwayLineupMidfield,
                strAwayLineupSubstitutes = input?.strAwayLineupSubstitutes,
                strAwayRedCards = input?.strAwayRedCards,
                strAwayTeam = input?.strAwayTeam,
                strAwayYellowCards = input?.strAwayYellowCards,
                strBanner = input?.strBanner,
                strCity = input?.strCity,
                strCountry = input?.strCountry,
                strDate = input?.strDate,
                strDescriptionEN = input?.strDescriptionEN,
                strEvent = input?.strEvent,
                strEventAlternate = input?.strEventAlternate,
                strFanart = input?.strFanart,
                strFilename = input?.strFilename,
                strHomeFormation = input?.strHomeFormation,
                strHomeGoalDetails = input?.strHomeGoalDetails,
                strHomeLineupDefense = input?.strHomeLineupDefense,
                strHomeLineupForward = input?.strHomeLineupForward,
                strHomeLineupGoalkeeper = input?.strHomeLineupGoalkeeper,
                strHomeLineupMidfield = input?.strHomeLineupMidfield,
                strHomeLineupSubstitutes = input?.strHomeLineupSubstitutes,
                strHomeRedCards = input?.strHomeRedCards,
                strHomeTeam = input?.strHomeTeam,
                strHomeYellowCards = input?.strHomeYellowCards,
                strLeague = input?.strLeague,
                strLocked = input?.strLocked,
                strMap = input?.strMap,
                strOfficial = input?.strOfficial,
                strPoster = input?.strPoster,
                strPostponed = input?.strPostponed,
                strResult = input?.strResult,
                strSeason = input?.strSeason,
                strSport = input?.strSport,
                strStatus = input?.strStatus,
                strTVStation = input?.strTVStation,
                strThumb = input?.strThumb,
                strTime = input?.strTime,
                strTimeLocal = input?.strTimeLocal,
                strTimestamp = input?.strTimestamp,
                strTweet1 = input?.strTweet1,
                strTweet2 = input?.strTweet2,
                strTweet3 = input?.strTweet3,
                strVenue = input?.strVenue,
                strVideo = input?.strVideo
            )
        }
    }

}